### ISSUE TITLE
Possible you write a library for ES8388  too?

### ISSUE THREAD

**Issue by dkotte** [Yveaux/AC101#10]
Your Ac101 library (this one) is used within great projects.
For example https://github.com/Edzelf/ESP32Radio-V2 .
But the hardware vendor of "AI Thinker audiokit" created new boards and now uses the ES8388. 
Now we search a library compatible to your AC101 library, full compatible with in initialization and commands.......  

THX Dirk

**Comment by Yveaux** [comment]
As you can see from the namen of the Ac101 library it was specifically written for this chip, more like a driver than an I2S audio library.
I have no plans to write a comparable driver for the ES8388 chip.

**Comment by garygru** [comment]
@dkotte have a look at [https://github.com/garygru/yummyDSP](https://github.com/garygru/yummyDSP). There is a driver for the ES8388 Codec included. It should work with the A1S Audio Kit. However, I did not test it. Good Luck, Gary
